eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8111
spring:
  application:
    name: c2
feign:
  hystrix:
    enabled: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: c1
    api-b:
      path: /api-b/**
      serviceId: c2